const restful = require('node-restful')
const mongoose = restful.mongoose

const retiradasSchema = new mongoose.Schema({
    status_item: { type: Number, default: 0},
    VALOR: { type: Number, },
    TIMESTAMP: { type: Date,  },
    DATA_CREDIARIO: { type: Date,  },
    HORA_CREDIARIO: { type: String,  },
    NOMECLI: { type: String,  },
    RELVENDA: { type: Number, },
    DATA: { type: Date,  },
    VENDEDOR: { type: String,  },
    D_ENTREGA: { type: Date,  },
    OBS: { type: String,  },
    BAIRRO: { type: String,  },
    CIDADE: { type: String,  },
    TIPO: { type: String,  },
    ENDERECO: { type: String,  },
    LOCAL_LOGISTICA: { type: Number, },
    REL: { type: Number, },
    // RELITEM: { type: Number, },
    // DESCRICAO: { type: String,  },
    // CAT: { type: Number, },
    // QTD: { type: Number, },
    // QTD_2: { type: Number, },
    // UNITARIO: { type: Number, },
    // PRECO: { type: Number, },
      //  RELCLI: { type: Number, },
  //  RELOBRA: { type: Number, },
 //   ENTREGUE: { type: Number, },
      //  CODIGO: { type: Number, },
    //  TOTALREC_LOCAL:{ type: Number, },
  //  NR_PROJETO:{ type: Number, },
  //  NR_ETAPA_PROJETO: { type: Number, },
  //  PERIODO_ENTR: { type: String,  },
//    QTD_MASTER: { type: Number, },
//   RELPEDVENDA: { type: Number, },
 //   RELMOVPEDVENDA: { type: Number, },
//  UNID_ENTREGA:{ type: Number, },
//   REL_PRODLOTE: { type: Number, },
//    PED_COMP: { type: Number, },
 //   QTD_COMP: { type: Number, },
 //   RELMOVENTR:{ type: Number, },
 //   CAIXA: { type: Number, },
 //   COD: { type: String,  },
    PRODUTOS: { type: Array, default: [] },
    idVendedor: { type: String, default: ''},
    idAdmin: { type: String, default: ''},
    messages: {type: Array, default: []},
    vendedorMsg: { type: Boolean, default: false},
    adminMsg: { type: Boolean, default: false},
    push: { type: Boolean, default: false},
    D_BAIXA: { type: Date, default: undefined}
})
module.exports = restful.model('Retiradas', retiradasSchema)
